// Managed by distribute-build; edits are replaced
// Code generated by distribute-build. DO NOT EDIT.
//
// It marks the repository as a library rather than a command. The
// library_marker build tag is never set by any build, so this file is never
// compiled and its package name binds nothing; its sole purpose is to exist.
// Tooling tells a library repository from a command repository by the presence
// of this file — do not remove it, and do not edit it: a change here is replaced
// whole, and the file is restored if it is deleted while the repository is still
// a library.

//go:build library_marker

package library_marker
